# Generated by Django 2.1.4 on 2019-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '漫画'), (2, '小説')], default=1, verbose_name='ジャンル')),
                ('name', models.CharField(max_length=200, verbose_name='書名')),
                ('author', models.CharField(max_length=200, verbose_name='著者')),
                ('grade', models.IntegerField(choices=[(1, 'very good'), (2, 'good'), (3, 'bad'), (4, 'very bad')], default=1, verbose_name='評価')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='感想')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
